[tool.poetry]
name = "adventofcode"
version = "0.1.0"
description = ""
authors = ["Raimar Sandner <mail@raimar-sandner.de>"]

[tool.poetry.dependencies]
python = ">=3.10,<3.11"
numpy = "^1.21.4"
pytest = "^6.2.5"
bitarray = "^2.3.4"
pytest-cases = "^3.6.5"
scipy = "^1.7.3"

[tool.poetry.dev-dependencies]
pytest-pycharm = "^0.7.0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
