[tool.poetry]
name = "adventofcode"
version = "0.1.0"
description = ""
authors = ["Raimar Sandner <mail@raimar-sandner.de>"]

[tool.poetry.dependencies]
python = ">=3.9,<3.11"
numpy = "^1.21.4"
pytest = "^6.2.5"
bitarray = "^2.3.4"
pytest-cases = "^3.6.5"
scipy = { version = "^1.7.3", optional = true }
more-itertools = "^9.0.0"
tinyarray = "^1.2.4"
networkx = "^2.8.8"

[tool.poetry.extras]
scipy = ["scipy"]

[tool.poetry.dev-dependencies]
pytest-pycharm = "^0.7.0"
pytest-profiling = "^1.7.0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
